#PDB Format from https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html
import numpy as np
import pandas as pd
import config
import os
from datetime import datetime
from Bio.PDB import PDBParser, Polypeptide
from Bio import PDB
from Bio.PDB.Polypeptide import protein_letters_3to1

def to_DF(pdbddata):
    df = pd.DataFrame(data=pdbddata)
    df = df.transpose()
    df.columns = ['Number','Name','ResName','Chain','ResId','X','Y','Z','Element']
    return df

def to_normal(df):
    Number = df['Number'].tolist()
    Name = df['Name'].tolist()
    ResName = df['ResName'].tolist()
    Chain = df['Chain'].tolist()
    ResId = df['ResId'].tolist()
    X = df['X'].tolist()
    Y = df['Y'].tolist()
    Z = df['Z'].tolist()
    Element = df['Element'].tolist()
    pdbdata=[Number,Name,ResName,Chain,ResId,X,Y,Z,Element]
    return pdbdata

def parse(f):
    Number = []
    Name = []
    ResName = []
    Chain = []
    ResId = []
    X = []
    Y = []
    Z = []
    Element = []
    pdbdata=[Number,Name,ResName,Chain,ResId,X,Y,Z,Element]
    with open(f, 'r') as f:
            lines = f.readlines()
            i=1
            for line in lines:
                if line.startswith("ATOM"):
                    pdbdata[0].append(int((line[6:11]).strip(" ")))
                    pdbdata[1].append((line[12:16]).strip(" "))
                    pdbdata[2].append((line[17:20]).strip(" "))
                    pdbdata[3].append((line[20:22]).strip(" "))
                    pdbdata[4].append(int((line[22:26]).strip(" ")))
                    pdbdata[5].append(float(line[30:38]))
                    pdbdata[6].append(float(line[38:46]))
                    pdbdata[7].append(float(line[46:54]))
                    pdbdata[8].append((line[76:78]).strip(" "))
                    i+=1
                if  line.startswith("END"):
                    break
    return pdbdata

def parse_gly(f):
    Number = []
    Name = []
    ResName = []
    Chain = []
    ResId = []
    X = []
    Y = []
    Z = []
    Element = []
    pdbdata=[Number,Name,ResName,Chain,ResId,X,Y,Z,Element]
    with open(f, 'r') as f:
            lines = f.readlines()
            i=1
            for line in lines:
                if line.startswith("HETATM"):
                    pdbdata[0].append(int((line[6:11]).strip(" ")))
                    pdbdata[1].append((line[12:16]).strip(" "))
                    pdbdata[2].append((line[17:20]).strip(" "))
                    pdbdata[3].append((line[20:22]).strip(" "))
                    pdbdata[4].append(int((line[22:26]).strip(" ")))
                    pdbdata[5].append(float(line[30:38]))
                    pdbdata[6].append(float(line[38:46]))
                    pdbdata[7].append(float(line[46:54]))
                    pdbdata[8].append((line[76:78]).strip(" "))
                    i+=1
                if  line.startswith("END"):
                    break
    return pdbdata



def exportPDB(fout,pdbdata,link_pairs):
    now = datetime.now()
    fn= open(fout,"w+")
    fn.write("REMARK    GENERATED BY Re-Glyco from GlycoShape\n")
    fn.write(f'REMARK    Time {now.strftime("%Y-%m-%d-%H:%M:%S")}\n')
    fn.write("REMARK ______    _______         _______  ___      __   __  _______  _______ \n")
    fn.write("REMARK|    _ |  |       |       |       ||   |    |  | |  ||       ||       |\n")
    fn.write("REMARK|   | ||  |    ___| ____  |    ___||   |    |  |_|  ||       ||   _   |\n")
    fn.write("REMARK|   |_||_ |   |___ |____| |   | __ |   |    |       ||       ||  | |  |\n")
    fn.write("REMARK|    __  ||    ___|       |   ||  ||   |___ |_     _||      _||  |_|  |\n")
    fn.write("REMARK|   |  | ||   |___        |   |_| ||       |  |   |  |     |_ |       |\n")
    fn.write("REMARK|___|  |_||_______|       |_______||_______|  |___|  |_______||_______|\n")
    fn.write("REMARK    https://github.com/Ojas-Singh/Re-Glyco\n")
    fn.write("REMARK    THIS FILE CONTAINS ONLY ATOMS\n")
    fn.write("REMARK   Cite:  GlycoShape: A 3D structures database and toolbox for glycomics and glycoanalytics\n")
    fn.write("REMARK          Callum M. Ives* and Ojas Singh*, Silvia D’Andrea, Carl A. Fogarty, Aoife M. Harbison, Akash Satheesan, Beatrice Tropea, Elisa Fadda\n")
    
    # Adding LINK records
    for link_pair in link_pairs:
        atom1, atom2 = link_pair
        # print(atom1,atom2)
        link_line = "LINK        {:>4} {:>3} {:1}{:>4}                {:>4} {:>3} {:1}{:>4}  \n".format(
    pdbdata[1][atom1], pdbdata[2][atom1], pdbdata[3][atom1], pdbdata[4][atom1],
    pdbdata[1][atom2], pdbdata[2][atom2], pdbdata[3][atom2], pdbdata[4][atom2])

        fn.write(link_line)
    
    k=""
    gly =False
    last_elements = [item[-1] for item in link_pairs]
    for i in range(len(pdbdata[0])):
        if i in last_elements:
                gly=True
                fn.write("TER\n")
        if not gly:
            line=list("ATOM".ljust(80))
        else:
            line=list("HETATM".ljust(80))
        line[6:10] = str(pdbdata[0][i]).rjust(5) 
        line[12:15] = str(pdbdata[1][i]).ljust(4) 
        line[17:19] = str(pdbdata[2][i]).rjust(3) 
        line[20:21] = str(pdbdata[3][i]).rjust(2) 
        line[22:25] = str(pdbdata[4][i]).rjust(4) 
        line[30:37] = str('{:0.3f}'.format(pdbdata[5][i])).rjust(8) 
        line[38:45] = str('{:0.3f}'.format(pdbdata[6][i])).rjust(8) 
        line[46:53] = str('{:0.3f}'.format(pdbdata[7][i])).rjust(8) 
        line[75:77] = str(pdbdata[8][i]).rjust(3) 
        line= ''.join(line)
        fn.write(line+"\n")
        k=k+line+"\n"
    
    # Adding CONECT records
    for connect_pair in link_pairs:
        atom1, atom2 = connect_pair
        conect_line = "CONECT{:>5}{:>5}\n".format(pdbdata[0][atom1], pdbdata[0][atom2])  # +1 because PDB is 1-indexed
        fn.write(conect_line)
    return k
                
def get_confidence(system):
    confidence= []
    p=1
    lines = system.split("\n")
    for x in lines:
        if x.startswith("ATOM"):
            if int((x[22:27]).strip(" "))==p:
                try: 
                    confidence.append(float((x[61:67]).strip(" ")))
                except:
                    confidence.append(0)
                p+=1
    return confidence


# {
#     "ALA": "A",
#     "ARG": "R",
#     "ASN": "N",
#     "ASP": "D",
#     "CYS": "C",
#     "GLU": "E",
#     "GLN": "Q",
#     "GLY": "G",
#     "HIS": "H",
#     "ILE": "I",
#     "LEU": "L",
#     "LYS": "K",
#     "MET": "M",
#     "PHE": "F",
#     "PRO": "P",
#     "SER": "S",
#     "THR": "T",
#     "TRP": "W",
#     "TYR": "Y",
#     "VAL": "V"
# }


# Step 1: Adjust get_sequence_from_pdb function

def get_sequence_from_pdb(file_path):
    parser = PDBParser(PERMISSIVE=1)
    structure = parser.get_structure('pdb', file_path)
    sequence_with_info = []  # List to store (residue, ResId, ChainId) tuples
    sequences = []
    
    for model in structure:
        for chain in model:
            chain_sequence = ""  
            for residue in chain:
                if residue.get_id()[0] == ' ':  # Skip over HETATM records
                    try:
                        aa = Polypeptide.three_to_one(residue.get_resname())
                        res_id = residue.get_id()[1]
                        chain_id = chain.get_id()
                        sequence_with_info.append((aa, res_id, chain_id))
                        chain_sequence += aa
                    except:
                        pass
            sequences.append(chain_sequence)
    return sequence_with_info, ' '.join(sequences)


# Step 2: Modify find_glycosylation_spots function

def find_glycosylation_spots(sequence_with_info):
    spots = []
    for i in range(len(sequence_with_info) - 2):
        curr_residue, _, _ = sequence_with_info[i]
        next_residue, _, _ = sequence_with_info[i+1]
        next_next_residue, _, _ = sequence_with_info[i+2]
        
        if curr_residue == 'N' and next_residue != 'P' and (next_next_residue == 'S' or next_next_residue == 'T'):
            spots.append((i + 1, sequence_with_info[i][1], sequence_with_info[i][2]))
        
        if curr_residue in ['T', 'W', 'S']:
            spots.append((i + 1, sequence_with_info[i][1], sequence_with_info[i][2]))
    
    return spots

def find_glycosylation_spots_N(sequence_with_info):
    spots = []
    for i in range(len(sequence_with_info) - 2):
        curr_residue, _, _ = sequence_with_info[i]
        next_residue, _, _ = sequence_with_info[i+1]
        next_next_residue, _, _ = sequence_with_info[i+2]
        
        if curr_residue == 'N' and next_residue != 'P' and (next_next_residue == 'S' or next_next_residue == 'T'):
            spots.append((i + 1, sequence_with_info[i][1], sequence_with_info[i][2]))

    return spots


def remove_hydrogens(input_pdb, output_pdb):
    # Initialize PDB parser
    parser = PDB.PDBParser()
    
    # Read the structure from the PDB file
    structure = parser.get_structure("structure", input_pdb)
    
    # Iterate over the atoms and remove hydrogens
    for model in structure:
        for chain in model:
            for residue in list(chain):
                for atom in list(residue):
                    if atom.element == "H":
                        residue.detach_child(atom.get_id())

    # Save the structure without hydrogens to a new PDB file
    io = PDB.PDBIO()
    io.set_structure(structure)
    io.save(output_pdb)



def swap_residues(pdb_filepath, asn_residue_list, output_filepath):
    """
    Swap the coordinates of ND2 and OD1 in ASN residues and write the output structure.

    Args:
    pdb_filepath (str): Path to the input PDB file.
    asn_residue_list (list): List of ASN residue numbers with chain identifiers (e.g., '132_B').
    output_filepath (str): Path to write the modified PDB file.
    """

    # Create a PDB parser
    parser = PDB.PDBParser()
    structure = parser.get_structure('structure', pdb_filepath)

    for residue_spec in asn_residue_list:
        res_num, chain_id = residue_spec.split('_')
        res_num = int(res_num)
        chain = structure[0][chain_id]  # Assuming the model is always 0

        if (res_num, chain_id) in [(res.get_id()[1], chain.id) for res in chain]:
            residue = chain[res_num]
            if residue.get_resname() == 'ASN':
                try:
                    # Swap the coordinates of ND2 and OD1
                    nd2_atom = residue['ND2']
                    od1_atom = residue['OD1']
                    nd2_coord, od1_coord = nd2_atom.get_coord(), od1_atom.get_coord()
                    nd2_atom.set_coord(od1_coord)
                    od1_atom.set_coord(nd2_coord)
                except KeyError:
                    print(f"Residue {residue} in chain {chain_id} does not have ND2 and OD1 atoms.")
            else:
                print(f"Residue {residue} in chain {chain_id} is not ASN.")
        else:
            print(f"Residue number {res_num} not found in chain {chain_id}.")

    # Write the output structure
    io = PDB.PDBIO()
    io.set_structure(structure)
    io.save(output_filepath)
