#PDB Format from https://www.cgl.ucsf.edu/chimera/docs/UsersGuide/tutorials/pdbintro.html
import numpy as np
import pandas as pd
import config
import os
from Bio.PDB import PDBParser, Polypeptide

def to_DF(pdbddata):
    df = pd.DataFrame(data=pdbddata)
    df = df.transpose()
    df.columns = ['Number','Name','ResName','Chain','ResId','X','Y','Z','Element']
    return df

def to_normal(df):
    Number = df['Number'].tolist()
    Name = df['Name'].tolist()
    ResName = df['ResName'].tolist()
    Chain = df['Chain'].tolist()
    ResId = df['ResId'].tolist()
    X = df['X'].tolist()
    Y = df['Y'].tolist()
    Z = df['Z'].tolist()
    Element = df['Element'].tolist()
    pdbdata=[Number,Name,ResName,Chain,ResId,X,Y,Z,Element]
    return pdbdata

def parse(f):
    Number = []
    Name = []
    ResName = []
    Chain = []
    ResId = []
    X = []
    Y = []
    Z = []
    Element = []
    pdbdata=[Number,Name,ResName,Chain,ResId,X,Y,Z,Element]
    with open(f, 'r') as f:
            lines = f.readlines()
            i=1
            for line in lines:
                if line.startswith("ATOM"):
                    pdbdata[0].append(int((line[7:11]).strip(" ")))
                    pdbdata[1].append((line[12:16]).strip(" "))
                    pdbdata[2].append((line[17:20]).strip(" "))
                    pdbdata[3].append((line[20:22]).strip(" "))
                    pdbdata[4].append(int((line[22:26]).strip(" ")))
                    pdbdata[5].append(float(line[31:38]))
                    pdbdata[6].append(float(line[39:46]))
                    pdbdata[7].append(float(line[47:54]))
                    pdbdata[8].append((line[76:78]).strip(" "))
                    i+=1
                if  line.startswith("END"):
                    break
    return pdbdata


def exportPDB(fout,pdbdata):
    fn= open(fout,"w+")
    fn.write("REMARK    GENERATED BY Re-Glyco from GlycoShape\n")
    fn.write(" ______    _______         _______  ___      __   __  _______  _______ \n")
    fn.write("|    _ |  |       |       |       ||   |    |  | |  ||       ||       |\n")
    fn.write("|   | ||  |    ___| ____  |    ___||   |    |  |_|  ||       ||   _   |\n")
    fn.write("|   |_||_ |   |___ |____| |   | __ |   |    |       ||       ||  | |  |\n")
    fn.write("|    __  ||    ___|       |   ||  ||   |___ |_     _||      _||  |_|  |\n")
    fn.write("|   |  | ||   |___        |   |_| ||       |  |   |  |     |_ |       |\n")
    fn.write("|___|  |_||_______|       |_______||_______|  |___|  |_______||_______|\n")
    fn.write("REMARK    https://github.com/Ojas-Singh/Re-Glyco\n")
    fn.write("REMARK    THIS FILE CONTAINS ONLY ATOMS\n")
    k=""
    for i in range(len(pdbdata[0])):
        line=list("ATOM".ljust(80))
        line[6:10] = str(pdbdata[0][i]).rjust(5) 
        line[12:15] = str(pdbdata[1][i]).ljust(4) 
        line[17:19] = str(pdbdata[2][i]).rjust(3) 
        line[20:21] = str(pdbdata[3][i]).rjust(2) 
        line[22:25] = str(pdbdata[4][i]).rjust(4) 
        line[30:37] = str('{:0.3f}'.format(pdbdata[5][i])).rjust(8) 
        line[38:45] = str('{:0.3f}'.format(pdbdata[6][i])).rjust(8) 
        line[46:53] = str('{:0.3f}'.format(pdbdata[7][i])).rjust(8) 
        line[75:77] = str(pdbdata[8][i]).rjust(3) 
        line= ''.join(line)
        fn.write(line+"\n")
        k=k+line+"\n"
    return k
                
def get_confidence(system):
    confidence= []
    p=1
    lines = system.split("\n")
    for x in lines:
        if x.startswith("ATOM"):
            if int((x[22:27]).strip(" "))==p:
                try: 
                    confidence.append(float((x[61:67]).strip(" ")))
                except:
                    confidence.append(0)
                p+=1
    return confidence


# {
#     "ALA": "A",
#     "ARG": "R",
#     "ASN": "N",
#     "ASP": "D",
#     "CYS": "C",
#     "GLU": "E",
#     "GLN": "Q",
#     "GLY": "G",
#     "HIS": "H",
#     "ILE": "I",
#     "LEU": "L",
#     "LYS": "K",
#     "MET": "M",
#     "PHE": "F",
#     "PRO": "P",
#     "SER": "S",
#     "THR": "T",
#     "TRP": "W",
#     "TYR": "Y",
#     "VAL": "V"
# }

def find_glycosylation_spots(sequence,shift):
    
    spots = []
    # We iterate until the third-to-last residue, so we can check three-residue sequences.
    for i in range(len(sequence) - 2):
        # Check if the current three residues match the N-X-S/T pattern, and X is not proline.
        if sequence[i] == 'N' and sequence[i + 1] != 'P' and (sequence[i + 2] == 'S' or sequence[i + 2] == 'T'):
            # Since residue numbers typically start at 1, we add 1 to the index.
            spots.append(i + 1 + shift)

        if sequence[i] == 'T' or sequence[i] =='Y' or sequence[i] == 'W' or sequence[i] == 'S':
            spots.append(i + 1 + shift)
    return spots


def get_sequence_from_pdb(file_path):
    protein = parse(file_path)
    df= to_DF(protein)
    parser = PDBParser(PERMISSIVE=1)
    structure = parser.get_structure('pdb', file_path)
    final_sequence =[]
    sequences = ''
    try:
        for model in structure:
            for chain in model:
                residues = []
                for residue in chain:
                    if residue.get_id()[0] == ' ':  # Skip over HETATM records
                        # residues.append(Polypeptide.three_to_one(residue.get_resname()))
                        sequences += Polypeptide.three_to_one(residue.get_resname())
    except:
        pass
    shift = df["ResId"][0]-1
    return sequences,shift