[server]
port = 80   
enableStaticServing = true

[browser]
gatherUsageStats = false


[theme]
primaryColor="#372C88"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"